export const floors = {
    "list": [{
      "pageAssemblyId":11,
      "context":{
        "style":"1", // 对应的是 code   1--单列图 2双列图  3三列图  4四列图
        "styleText":"这个最好不用 - 仅仅用来做debug看接口用的 单列图",
        "hasBackground":"1", //1-有背景/0-无背景
        "bgColor":"#0094ff", // 背景色
        "bgImage":"", // 背景图片url
        "backgroundType":"1", // 背景类型 决定取上面的哪个字段展示， 到底是背景颜色还是背景图片
        "showComTitle":"1",// 0隐藏名称-1显示名称
        "comTitle":"单列图",
        "list":[
            {
                "category":null,
                "showPrice":0,
                "skuId":null,
                "textBg":"",
                "textColor":"",
                "price":"99.99",
                "url":"https://wanshunjiaoche-file-public-1301582899.cos.ap-guangzhou.myqcloud.com/oaPermissionConsoleImpl/5/1679992827758_iZM7x.jpg",
                "miniAppLink":"小程序的路径",
                "deepLink":"app的路径",
                "h5Link":"h5地址"
            }
        ]
      }
    },
    {
        "pageAssemblyId":3,
        "context":{
          "style":"2", // 对应的是 code   1--单列图 2双列图  3三列图  4四列图
          "styleText":"这个最好不用 - 仅仅用来做debug看接口用的 单列图",
          "hasBackground":"1", //1-有背景/0-无背景
          "bgColor":"#0094ff", // 背景色
          "bgImage":"", // 背景图片url
          "backgroundType":"1", // 背景类型 决定取上面的哪个字段展示， 到底是背景颜色还是背景图片
          "showComTitle":"1",// 0隐藏名称-1显示名称
          "comTitle":"双列图",
          "list":[
            {
                "category":null,
                "showPrice":0,
                "skuId":null,
                "textBg":"",
                "textColor":"",
                "price":"99.99",
                "url":"https://wanshunjiaoche-file-public-1301582899.cos.ap-guangzhou.myqcloud.com/oaPermissionConsoleImpl/5/1679992827758_iZM7x.jpg",
                "miniAppLink":"小程序的路径",
                "deepLink":"app的路径",
                "h5Link":"h5地址"
            },
            {
                "category":null,
                "showPrice":0,
                "skuId":null,
                "textBg":"",
                "textColor":"",
                "price":"99.99",
                "url":"",
                "miniAppLink":"小程序的路径",
                "deepLink":"app的路径",
                "h5Link":"h5地址"
            }
          ]
        }
      },
      {
        "pageAssemblyId":4,
        "context":{
          "style":"3", // 对应的是 code   1--单列图 2双列图  3三列图  4四列图
          "styleText":"这个最好不用 - 仅仅用来做debug看接口用的 单列图",
          "hasBackground":"1", //1-有背景/0-无背景
          "bgColor":"#0094ff", // 背景色
          "bgImage":"", // 背景图片url
          "backgroundType":"1", // 背景类型 决定取上面的哪个字段展示， 到底是背景颜色还是背景图片
          "showComTitle":"1",// 0隐藏名称-1显示名称
          "comTitle":"三列图",
          "list":[
            {
                "category":null,
                "showPrice":0,
                "skuId":null,
                "textBg":"",
                "textColor":"",
                "price":"99.99",
                "url":"https://wanshunjiaoche-file-public-1301582899.cos.ap-guangzhou.myqcloud.com/oaPermissionConsoleImpl/5/1679992827758_iZM7x.jpg",
                "miniAppLink":"小程序的路径",
                "deepLink":"app的路径",
                "h5Link":"h5地址"
            },
            {
                "category":null,
                "showPrice":0,
                "skuId":null,
                "textBg":"",
                "textColor":"",
                "price":"99.99",
                "url":"https://wanshunjiaoche-file-public-1301582899.cos.ap-guangzhou.myqcloud.com/oaPermissionConsoleImpl/5/1679992827758_iZM7x.jpg",
                "miniAppLink":"小程序的路径",
                "deepLink":"app的路径",
                "h5Link":"h5地址"
            },
            {
                "category":null,
                "showPrice":0,
                "skuId":null,
                "textBg":"",
                "textColor":"",
                "price":"99.99",
                "url":"",
                "miniAppLink":"小程序的路径",
                "deepLink":"app的路径",
                "h5Link":"h5地址"
            }
          ]
        }
      },
      {
        "pageAssemblyId":7,
        "context":{
          "style":"4", // 对应的是 code   1--单列图 2双列图  3三列图  4四列图
          "styleText":"这个最好不用 - 仅仅用来做debug看接口用的 单列图",
          "hasBackground":"1", //1-有背景/0-无背景
          "bgColor":"#0094ff", // 背景色
          "bgImage":"", // 背景图片url
          "backgroundType":"1", // 背景类型 决定取上面的哪个字段展示， 到底是背景颜色还是背景图片
          "showComTitle":"1",// 0隐藏名称-1显示名称
          "comTitle":"四列图",
          "list":[
            {
                "category":null,
                "showPrice":0,
                "skuId":null,
                "textBg":"",
                "textColor":"",
                "price":"99.99",
                "url":"https://wanshunjiaoche-file-public-1301582899.cos.ap-guangzhou.myqcloud.com/oaPermissionConsoleImpl/5/1679992827758_iZM7x.jpg",
                "miniAppLink":"小程序的路径",
                "deepLink":"app的路径",
                "h5Link":"h5地址"
            },
            {
                "category":null,
                "showPrice":0,
                "skuId":null,
                "textBg":"",
                "textColor":"",
                "price":"99.99",
                "url":"",
                "miniAppLink":"小程序的路径",
                "deepLink":"app的路径",
                "h5Link":"h5地址"
            },{
                "category":null,
                "showPrice":0,
                "skuId":null,
                "textBg":"",
                "textColor":"",
                "price":"99.99",
                "url":"",
                "miniAppLink":"小程序的路径",
                "deepLink":"app的路径",
                "h5Link":"h5地址"
            },{
                "category":null,
                "showPrice":0,
                "skuId":null,
                "textBg":"",
                "textColor":"",
                "price":"99.99",
                "url":"",
                "miniAppLink":"小程序的路径",
                "deepLink":"app的路径",
                "h5Link":"h5地址"
            }
          ]
        }
      },
    {
      "pageAssemblyId":8,
      "context":{
        "key":"float-notice",
        "text":"浮动按钮",
        "icon":"https://wsjc-web-1301582899.cos.ap-guangzhou.myqcloud.com/wsf-mall/mallConfigSystem/mall-config-feature-icon-float.webp",
        "showConfig":true,
        "drag":true,
        "delete":true,
        "url":"https://wanshunjiaoche-file-public-1301582899.cos.ap-guangzhou.myqcloud.com/oaPermissionConsoleImpl/5/1686919617530_DtKGw.png",
        "miniAppLink":"",
        "deepLink":"",
        "h5Link":"",
        "linkType":1,
        "jumpLinkTypeRadio":1,
        "groupName":"广告组件",
        "_uuid":"155a6eaf-a5a1-41d2-b130-a64d1b15225c",
        "link":"123631"
      } 
    },
    {
        "pageAssemblyId":15,
        "context":{
            "key":"left-to-right-slider",
            "text":"左右滑动",
            "showConfig":true,
            "drag":true,
            "delete":true,
            "style":1,
            "list":[
                {
                    "id":"fc9b5bb1-9d59-4fcf-8509-ff3b2d10d03a",
                    "url":"",
                    "text":"adada",
                    "textColor":"",
                    "miniAppLink":"",
                    "deepLink":"",
                    "h5Link":"",
                    "linkType":1,
                    "jumpLinkTypeRadio":1
                },
                {
                    "id":"28f77241-319b-4f85-a7e5-cc35129296e9",
                    "url":"",
                    "text":"d",
                    "textColor":"",
                    "miniAppLink":"",
                    "deepLink":"",
                    "h5Link":"",
                    "linkType":"",
                    "jumpLinkTypeRadio":1
                },
                {
                    "id":"629ebed6-3347-4c0d-9932-ee31962eea01",
                    "url":"",
                    "text":"",
                    "textColor":"",
                    "miniAppLink":"",
                    "deepLink":"",
                    "h5Link":"",
                    "linkType":"",
                    "jumpLinkTypeRadio":1
                },
                {
                    "id":"5b027299-e6d0-43f5-9c46-cada2ff71b4b",
                    "url":"",
                    "text":"",
                    "textColor":"",
                    "miniAppLink":"",
                    "deepLink":"",
                    "h5Link":"",
                    "linkType":"",
                    "jumpLinkTypeRadio":1
                },
                {
                    "id":"222368cb-c573-498a-9f79-77e163f9c0df",
                    "url":"",
                    "text":"",
                    "textColor":"",
                    "miniAppLink":"",
                    "deepLink":"",
                    "h5Link":"",
                    "linkType":"",
                    "jumpLinkTypeRadio":1
                }
            ],
            "icon":"https://wsjc-web-1301582899.cos.ap-guangzhou.myqcloud.com/wsf-mall/os-config/goods-com-left-to-right.webp",
            "groupName":"功能组件",
            "_uuid":"586ae079-c229-45be-a3ff-10f2a6ef546f"
        }
    },
    {
        "pageAssemblyId":16,
        "context":{
            "key":"top-to-bottom-slider",
            "text":"上下自增",
            "showConfig":true,
            "drag":true,
            "delete":true,
            "style":2,
            "list":[
                {
                    "id":"fc9b5bb1-9d59-4fcf-8509-ff3b2d10d03a",
                    "url":"",
                    "text":"adada",
                    "textColor":"",
                    "miniAppLink":"",
                    "deepLink":"",
                    "h5Link":"",
                    "linkType":1,
                    "jumpLinkTypeRadio":1
                },
                {
                    "id":"28f77241-319b-4f85-a7e5-cc35129296e9",
                    "url":"",
                    "text":"d",
                    "textColor":"",
                    "miniAppLink":"",
                    "deepLink":"",
                    "h5Link":"",
                    "linkType":"",
                    "jumpLinkTypeRadio":1
                },
                {
                    "id":"629ebed6-3347-4c0d-9932-ee31962eea01",
                    "url":"",
                    "text":"",
                    "textColor":"",
                    "miniAppLink":"",
                    "deepLink":"",
                    "h5Link":"",
                    "linkType":"",
                    "jumpLinkTypeRadio":1
                },
                {
                    "id":"5b027299-e6d0-43f5-9c46-cada2ff71b4b",
                    "url":"",
                    "text":"",
                    "textColor":"",
                    "miniAppLink":"",
                    "deepLink":"",
                    "h5Link":"",
                    "linkType":"",
                    "jumpLinkTypeRadio":1
                },
                {
                    "id":"222368cb-c573-498a-9f79-77e163f9c0df",
                    "url":"",
                    "text":"33ss",
                    "textColor":"",
                    "miniAppLink":"",
                    "deepLink":"",
                    "h5Link":"",
                    "linkType":"",
                    "jumpLinkTypeRadio":1
                }
            ],
            "icon":"https://wsjc-web-1301582899.cos.ap-guangzhou.myqcloud.com/wsf-mall/os-config/goods-com-left-to-right.webp",
            "groupName":"功能组件",
            "_uuid":"586ae079-c229-45be-a3ff-10f2a6ef546f"
        }
    },
    {
        "pageAssemblyId":2,
        "context":{
            "key":"carousel",
            "text":"轮播图",
            "icon":"https://wsjc-web-1301582899.cos.ap-guangzhou.myqcloud.com/wsf-mall/mallConfigSystem/mall-config-feature-icon-swiper.webp",
            "showConfig":true,
            "drag":true,
            "delete":true,
            "type":"horizontal",
            "direction":"horizontal",
            "time":3000,
            "height":"60px",
            "hidePoint":false,
            "list":[
                {
                    "id":"f3f6a222-9760-473b-a356-470ed525c4e2",
                    "url":"",
                    "miniAppLink":"",
                    "deepLink":"",
                    "h5Link":"",
                    "linkType":"",
                    "jumpLinkTypeRadio":1
                },
                {
                    "id":"e9759d5a-8edb-4baa-a035-6e8eb539133e",
                    "url":"",
                    "miniAppLink":"",
                    "deepLink":"",
                    "h5Link":"",
                    "linkType":"",
                    "jumpLinkTypeRadio":1
                },
                {
                    "id":"ab86533b-3f01-4b2a-b500-7551171aecd7",
                    "url":"",
                    "miniAppLink":"",
                    "deepLink":"",
                    "h5Link":"",
                    "linkType":"",
                    "jumpLinkTypeRadio":1
                }
            ],
            "groupName":"广告组件",
            "_uuid":"f8c1e11a-0891-4da4-80ef-886c7fff9f3b"
        }
    },
    {
        "pageAssemblyId":5,
        "context":{
            "key":"group-2-image",
            "text":"半屏双列图",
            "icon":"",
            "showConfig":true,
            "drag":true,
            "delete":true,
            "hasBackground":"1",// 1-有背景/0-无背景
            "backgroundType":"1", // 0 --背景颜色   1-背景图片
            "showComTitle":"1", // 0 隐藏名称-1显示名称
            "list":[
                {
                    "comTitle":"组件标题-左边的",
                    "bgColor":"",
                    "bgImage":"https://wsjc-web-1301582899.cos.ap-guangzhou.myqcloud.com/wsf-mall/mallConfigSystem/mall-config-feature-icon-swiper.webp",
                    "list":[
                        {
                            "id":"3f42058f-aa70-4e95-8bfb-2192793ae43d",
                            "url":"",
                            "miniAppLink":"",
                            "deepLink":"",
                            "h5Link":"",
                            "linkType":"",
                            "jumpLinkTypeRadio":1,
                            "category":null,
                            "showPrice":0,
                            "skuId":null,
                            "textBg":"文字背景颜色",
                            "textColor":"文字颜色",
                            "price":"商品价格"
                        },
                        {
                            "id":"3f42058f-aa70-4e95-8bfb-xx",
                            "url":"",
                            "miniAppLink":"",
                            "deepLink":"",
                            "h5Link":"",
                            "linkType":"",
                            "jumpLinkTypeRadio":1,
                            "category":null,
                            "showPrice":0,
                            "skuId":null,
                            "textBg":"文字背景颜色",
                            "textColor":"文字颜色",
                            "price":"商品价格"
                        }
                    ]
                },
                {
                    "comTitle":"组件标题-右边的",
                    "bgColor":"",
                    "bgImage":"https://wsjc-web-1301582899.cos.ap-guangzhou.myqcloud.com/wsf-mall/mallConfigSystem/mall-config-feature-icon-swiper.webp",
                    "list":[
                        {
                            "id":"3f42058f-aa70-4e95-8bfb-2192793ae43d",
                            "url":"",
                            "miniAppLink":"",
                            "deepLink":"",
                            "h5Link":"",
                            "linkType":"",
                            "jumpLinkTypeRadio":1,
                            "category":null,
                            "showPrice":0,
                            "skuId":null,
                            "textBg":"文字背景颜色",
                            "textColor":"文字颜色",
                            "price":"商品价格"
                        },
                        {
                            "id":"3f42058f-aa70-4e95-8bfb-xx",
                            "url":"",
                            "miniAppLink":"",
                            "deepLink":"",
                            "h5Link":"",
                            "linkType":"",
                            "jumpLinkTypeRadio":1,
                            "category":null,
                            "showPrice":0,
                            "skuId":null,
                            "textBg":"文字背景颜色",
                            "textColor":"文字颜色",
                            "price":"商品价格"
                        }
                    ]
                }
            ],
            "groupName":"广告组件",
            "_uuid":"79e17790-2208-48f3-b0e3-8b523fd0b0ec"
        }
    },
    {
        "pageAssemblyId":6,
        "context":{
            "key":"slider",
            "text":"滑动区块",
            "icon":"https://wsjc-web-1301582899.cos.ap-guangzhou.myqcloud.com/wsf-mall/mallConfigSystem/mall-config-feature-icon-slither.webp",
            "showConfig":true,
            "drag":true,
            "delete":true,
            "showComTitle":"1",
            "comTitle":"dddd",
            "hasBackground":"1",
            "bgColor":"#FFFFFF",
            "bgImage":"",
            "backgroundType":"0",
            "list":[
                {
                    "category":null,
                    "showPrice":0,
                    "skuId":null,
                    "textBg":"文字背景颜色",
                    "textColor":"文字颜色",
                    "price":"商品价格",
                    "id":"666c4881-0d56-4933-b628-0f42cd9cd488",
                    "url":"",
                    "miniAppLink":"",
                    "deepLink":"",
                    "h5Link":"",
                    "linkType":"",
                    "jumpLinkTypeRadio":1
                },
                {
                    "id":"98d80972-8fce-46ad-90b6-2848f9dc933c",
                    "url":"",
                    "miniAppLink":"",
                    "deepLink":"",
                    "h5Link":"",
                    "linkType":"",
                    "jumpLinkTypeRadio":1
                },
                {
                    "id":"8272839f-b245-4c30-a2ad-82d243419969",
                    "url":"",
                    "miniAppLink":"",
                    "deepLink":"",
                    "h5Link":"",
                    "linkType":"",
                    "jumpLinkTypeRadio":1
                },
                {
                    "id":"fbb35f9e-b19b-40e3-ab52-d50580f6594f",
                    "url":"",
                    "miniAppLink":"",
                    "deepLink":"",
                    "h5Link":"",
                    "linkType":"",
                    "jumpLinkTypeRadio":1
                }
            ],
            "groupName":"广告组件",
            "_uuid":"03fc7ef8-d2dd-4007-b16e-e158054a2c09"
        }
    },
    {
        "pageAssemblyId":9,
        "context":{
            "key":"cube-image",
            "text":"图片魔方",
            "icon":"https://wsjc-web-1301582899.cos.ap-guangzhou.myqcloud.com/wsf-mall/mallConfigSystem/mall-config-feature-icon-magic.webp",
            "showConfig":true,
            "drag":true,
            "delete":true,
            "style":1,
            "styleText":"图片魔方风格1",
            "backgroundType":"0",
            "bgColor":"#6DD016",
            "bgImage":"",
            "hasBackground":"1",
            "showComTitle":"1",
            "comTitle":"魔方组件标题",
            "slideshowImageListId":0,
            "hidePoint":false,
            "slideshowImageList":[
                {
                    "url":"https://wanshunjiaoche-file-public-1301582899.cos.ap-guangzhou.myqcloud.com/oaPermissionConsoleImpl/5/1687182025157_f8vHX.jpg",
                    "miniAppLink":"/app/sdsdasad/1",
                    "deepLink":"wsjc://300/home",
                    "h5Link":"",
                    "linkType":1,
                    "jumpLinkTypeRadio":1
                },
                {
                    "url":"https://wanshunjiaoche-file-public-1301582899.cos.ap-guangzhou.myqcloud.com/oaPermissionConsoleImpl/5/1687182149839_kL0hc.jpg",
                    "miniAppLink":"",
                    "deepLink":"",
                    "h5Link":"",
                    "linkType":"",
                    "jumpLinkTypeRadio":1
                },
                {
                    "url":"https://wanshunjiaoche-file-public-1301582899.cos.ap-guangzhou.myqcloud.com/oaPermissionConsoleImpl/5/1687182153194_MbCvF.jpg",
                    "miniAppLink":"",
                    "deepLink":"",
                    "h5Link":"",
                    "linkType":"",
                    "jumpLinkTypeRadio":1
                }
            ],
            "list":[
                {
                    "id":"57406375-c27c-4276-a315-f2da61d09786",
                    "url":"https://wanshunjiaoche-file-public-1301582899.cos.ap-guangzhou.myqcloud.com/oaPermissionConsoleImpl/5/1687182145308_HmWG8.png",
                    "miniAppLink":"productModule/pages/skuDetail/skuDetail?skuId=168682244179450",
                    "deepLink":"",
                    "h5Link":"https://m.wsfmall.com/spudetail?id=168682244179450",
                    "linkType":1,
                    "jumpLinkTypeRadio":1
                },
                {
                    "id":"890e532e-1bd5-4813-b7d5-df217888ea5b",
                    "url":"https://wanshunjiaoche-file-public-1301582899.cos.ap-guangzhou.myqcloud.com/oaPermissionConsoleImpl/5/1687182138861_pNUhU.png",
                    "miniAppLink":"",
                    "deepLink":"",
                    "h5Link":"http://baidu.com",
                    "linkType":3,
                    "jumpLinkTypeRadio":3
                }
            ],
            "groupName":"广告组件",
            "_uuid":"578f402e-659a-4273-b7dd-9d81a8f4ae54"
        }
    },
    {
        "pageAssemblyId":10,
        "context":{
            "key":"proclamation",
            "text":"公告",
            "icon":"https://wsjc-web-1301582899.cos.ap-guangzhou.myqcloud.com/wsf-mall/mallConfigSystem/mall-config-feature-icon-news.webp",
            "showConfig":true,
            "drag":true,
            "delete":true,
            "iconUrl":"https://wsjc-web-1301582899.cos.ap-guangzhou.myqcloud.com/wsf-mall/mallConfigSystem/announcement.png",
            "bgColor":"#FFFFFF",
            "bgImage":"",
            "textarea":"公告 / 通知栏, 内容过长时向左滚动显示 公告 / 通知栏, 内容过长时向左滚动显示 公告 / 通知栏, 内容过长时向左滚动显示",
            "color":"#000",
            "linkImage":"https://wsjc-web-1301582899.cos.ap-guangzhou.myqcloud.com/wsf-mall/mallConfigSystem/announcementMore.png",            
            "miniAppLink":"小程序的路径",
            "deepLink":"app的路径",
            "h5Link":"h5地址",
            "linkType":"",
            "groupName":"广告组件"
        }
    },
    {
        "pageAssemblyId": 13,
        "context":{
            "key":"one-column-goods",
            "list":[
                "12",
                "33"
            ],
            "maxCount":12
        }
    }
    ],
    "headerData": {
        headerBg: {
          bgColor: '#0094ff',
          bgImage: '',
          backgroundType: '0'
        },
        pageNavBg: {
          bgColor: 'pink',
          bgImage: '',
          backgroundType: '0'
        },
    
        // 页眉广告
        smallAdList: [
          {
            url: 'https://wsjc-web-1301582899.cos.ap-guangzhou.myqcloud.com/ws-smart-life/home/smart_home_title.png',
            miniAppLink: "小程序的路径",
            deepLink:"app的路径",
            h5Link: "h5地址",
            linkType: ""
          },
          {
            url: 'https://wsjc-web-1301582899.cos.ap-guangzhou.myqcloud.com/ws-smart-life/home/smart_home_title.png',
            miniAppLink: "小程序的路径",
            deepLink:"app的路径",
            h5Link: "h5地址",
            linkType: ""
          }
        ]
    }
}