export const detailData = {
  id: "16082776626282700",
  spuId: "270",
  name: "可小刀(开刃)",
  subTitle: "",
  images: [
    "https://wanshunfu-1301582899.cos.ap-guangzhou.myqcloud.com///acbdc92b567048edc00ce6a223f272ae.jpg?fileUid=1608277448612",
  ],
  price: 1000.0,
  oldPrice: 1000.0,
  stock: 100,
  skuSpecValues: [
    {
      id: "7012",
      spuId: "270",
      skuId: "16082776626282700",
      specId: "17",
      specValueId: "76",
      valueRemark: "开刃",
      delFlag: "0",
      specValueSource: 0,
      spec: {
        id: "17",
        name: "军事用品",
        nickName: "危险 慎用",
        delFlag: "0",
        createName: "admin",
        modifyName: null,
        delName: null,
        createTime: null,
        modifyTime: null,
        delTime: null,
        specValues: null,
      },
    },
  ],
  storeName: "古天乐的杂货铺",
  storeId: "17",
  skuNo: "1608277462000",
  typeId: "10",
  isGift: "0",
  isVirtual: "0",
  spuServiceSupports: [],
  spuAttributeValues: [
    {
      id: "3224",
      spuId: "270",
      attributeId: "15989506011436333",
      attributeName: "肥肥",
      attributeValueId: "196919",
      attributeValue: "肥",
      delFlag: "0",
    },
  ],
  specList: null,
  skuList: [
    {
      id: "16082776626282700",
      spuId: "270",
      skuNo: "1608277462000",
      name: "可小刀(开刃)",
      subTitle: "",
      stock: 100,
      warningStock: 10,
      supplyPrice: null,
      guidePrice: null,
      price: 1000.0,
      weight: 1000.0,
      storeId: "17",
      storeName: null,
      isDefault: 0,
      isBatchSku: 0,
      shelvesStatus: "1",
      isGift: "0",
      isVirtual: "0",
      reason: null,
      delFlag: "0",
      createName: null,
      modifyName: null,
      delName: null,
      createTime: null,
      modifyTime: null,
      delTime: null,
      isShow: 1,
      accumulativeStock: 0,
      url: "https://wanshunfu-1301582899.cos.ap-guangzhou.myqcloud.com///acbdc92b567048edc00ce6a223f272ae.jpg?fileUid=1608277448612",
      status: "0",
      firstCateId: "62",
      secondCateId: "63",
      thirdCateId: "64",
      upTime: "2020-12-30 16:45:29",
      skuImages: [
        {
          id: "5364",
          spuId: "270",
          skuId: "16082776626282700",
          url: "https://wanshunfu-1301582899.cos.ap-guangzhou.myqcloud.com///acbdc92b567048edc00ce6a223f272ae.jpg?fileUid=1608277448612",
          defaultFlag: null,
          delFlag: "0",
        },
      ],
      skuSpecValues: [
        {
          id: "7012",
          spuId: "270",
          skuId: "16082776626282700",
          specId: "17",
          specValueId: "76",
          valueRemark: "开刃",
          delFlag: "0",
          specValueSource: 0,
          spec: {
            id: "17",
            name: "军事用品",
            nickName: "危险 慎用",
            delFlag: "0",
            createName: "admin",
            modifyName: null,
            delName: null,
            createTime: null,
            modifyTime: null,
            delTime: null,
            specValues: null,
          },
        },
      ],
      nameSkus: null,
      initialSku: null,
      tree: null,
      specValues: null,
      remark: null,
      mobileDesc: null,
      logisticsTemplateId: "14",
      performanceScore: 0,
      skuNum: null,
      unitId: null,
      grossProfitMargin: null,
      supplyPriceFlag: false,
      guidePriceFlag: false,
      ownerPs: null,
      storePs: null,
      platformMargin: null,
      specialPrice: null,
      goodsSource: 1,
      idNumber: null,
      purchasePrice: null,
      isGiftSku: null,
    },
    {
      id: "16082776626282701",
      spuId: "270",
      skuNo: "1608277462001",
      name: "可小刀(未开刃)",
      subTitle: "",
      stock: 100,
      warningStock: 10,
      supplyPrice: null,
      guidePrice: null,
      price: 1000.0,
      weight: 1100.0,
      storeId: "17",
      storeName: null,
      isDefault: 1,
      isBatchSku: 0,
      shelvesStatus: "1",
      isGift: "0",
      isVirtual: "0",
      reason: null,
      delFlag: "0",
      createName: null,
      modifyName: null,
      delName: null,
      createTime: null,
      modifyTime: null,
      delTime: null,
      isShow: 1,
      accumulativeStock: 0,
      url: "https://wanshunfu-1301582899.cos.ap-guangzhou.myqcloud.com///acbdc92b567048edc00ce6a223f272ae.jpg?fileUid=1608277448612",
      status: "0",
      firstCateId: "62",
      secondCateId: "63",
      thirdCateId: "64",
      upTime: "2020-12-30 16:45:29",
      skuImages: [
        {
          id: "5365",
          spuId: "270",
          skuId: "16082776626282701",
          url: "https://wanshunfu-1301582899.cos.ap-guangzhou.myqcloud.com///acbdc92b567048edc00ce6a223f272ae.jpg?fileUid=1608277448612",
          defaultFlag: null,
          delFlag: "0",
        },
      ],
      skuSpecValues: [
        {
          id: "7013",
          spuId: "270",
          skuId: "16082776626282701",
          specId: "17",
          specValueId: "77",
          valueRemark: "未开刃",
          delFlag: "0",
          specValueSource: 0,
          spec: {
            id: "17",
            name: "军事用品",
            nickName: "危险 慎用",
            delFlag: "0",
            createName: "admin",
            modifyName: null,
            delName: null,
            createTime: null,
            modifyTime: null,
            delTime: null,
            specValues: null,
          },
        },
      ],
      nameSkus: null,
      initialSku: null,
      tree: null,
      specValues: null,
      remark: null,
      mobileDesc: null,
      logisticsTemplateId: "14",
      performanceScore: 0,
      skuNum: null,
      unitId: null,
      grossProfitMargin: null,
      supplyPriceFlag: false,
      guidePriceFlag: false,
      ownerPs: null,
      storePs: null,
      platformMargin: null,
      specialPrice: null,
      goodsSource: 1,
      idNumber: null,
      purchasePrice: null,
      isGiftSku: null,
    },
  ],
  validSkuList: [
    {
      id: "16082776626282700",
      spuId: "270",
      skuNo: "1608277462000",
      name: "可小刀(开刃)",
      subTitle: "",
      stock: 100,
      warningStock: 10,
      supplyPrice: null,
      guidePrice: null,
      price: 1000.0,
      weight: 1000.0,
      storeId: "17",
      storeName: null,
      isDefault: 0,
      isBatchSku: 0,
      shelvesStatus: "1",
      isGift: "0",
      isVirtual: "0",
      reason: null,
      delFlag: "0",
      createName: null,
      modifyName: null,
      delName: null,
      createTime: null,
      modifyTime: null,
      delTime: null,
      isShow: 1,
      accumulativeStock: 0,
      url: "https://wanshunfu-1301582899.cos.ap-guangzhou.myqcloud.com///acbdc92b567048edc00ce6a223f272ae.jpg?fileUid=1608277448612",
      status: "0",
      firstCateId: "62",
      secondCateId: "63",
      thirdCateId: "64",
      upTime: "2020-12-30 16:45:29",
      skuImages: [
        {
          id: "5364",
          spuId: "270",
          skuId: "16082776626282700",
          url: "https://wanshunfu-1301582899.cos.ap-guangzhou.myqcloud.com///acbdc92b567048edc00ce6a223f272ae.jpg?fileUid=1608277448612",
          defaultFlag: null,
          delFlag: "0",
        },
      ],
      skuSpecValues: [
        {
          id: "7012",
          spuId: "270",
          skuId: "16082776626282700",
          specId: "17",
          specValueId: "76",
          valueRemark: "开刃",
          delFlag: "0",
          specValueSource: 0,
          spec: {
            id: "17",
            name: "军事用品",
            nickName: "危险 慎用",
            delFlag: "0",
            createName: "admin",
            modifyName: null,
            delName: null,
            createTime: null,
            modifyTime: null,
            delTime: null,
            specValues: null,
          },
        },
      ],
      nameSkus: null,
      initialSku: null,
      tree: null,
      specValues: null,
      remark: null,
      mobileDesc: null,
      logisticsTemplateId: "14",
      performanceScore: 0,
      skuNum: null,
      unitId: null,
      grossProfitMargin: null,
      supplyPriceFlag: false,
      guidePriceFlag: false,
      ownerPs: null,
      storePs: null,
      platformMargin: null,
      specialPrice: null,
      goodsSource: 1,
      idNumber: null,
      purchasePrice: null,
      isGiftSku: null,
    },
    {
      id: "16082776626282701",
      spuId: "270",
      skuNo: "1608277462001",
      name: "可小刀(未开刃)",
      subTitle: "",
      stock: 100,
      warningStock: 10,
      supplyPrice: null,
      guidePrice: null,
      price: 1000.0,
      weight: 1100.0,
      storeId: "17",
      storeName: null,
      isDefault: 1,
      isBatchSku: 0,
      shelvesStatus: "1",
      isGift: "0",
      isVirtual: "0",
      reason: null,
      delFlag: "0",
      createName: null,
      modifyName: null,
      delName: null,
      createTime: null,
      modifyTime: null,
      delTime: null,
      isShow: 1,
      accumulativeStock: 0,
      url: "https://wanshunfu-1301582899.cos.ap-guangzhou.myqcloud.com///acbdc92b567048edc00ce6a223f272ae.jpg?fileUid=1608277448612",
      status: "0",
      firstCateId: "62",
      secondCateId: "63",
      thirdCateId: "64",
      upTime: "2020-12-30 16:45:29",
      skuImages: [
        {
          id: "5365",
          spuId: "270",
          skuId: "16082776626282701",
          url: "https://wanshunfu-1301582899.cos.ap-guangzhou.myqcloud.com///acbdc92b567048edc00ce6a223f272ae.jpg?fileUid=1608277448612",
          defaultFlag: null,
          delFlag: "0",
        },
      ],
      skuSpecValues: [
        {
          id: "7013",
          spuId: "270",
          skuId: "16082776626282701",
          specId: "17",
          specValueId: "77",
          valueRemark: "未开刃",
          delFlag: "0",
          specValueSource: 0,
          spec: {
            id: "17",
            name: "军事用品",
            nickName: "危险 慎用",
            delFlag: "0",
            createName: "admin",
            modifyName: null,
            delName: null,
            createTime: null,
            modifyTime: null,
            delTime: null,
            specValues: null,
          },
        },
      ],
      nameSkus: null,
      initialSku: null,
      tree: null,
      specValues: null,
      remark: null,
      mobileDesc: null,
      logisticsTemplateId: "14",
      performanceScore: 0,
      skuNum: null,
      unitId: null,
      grossProfitMargin: null,
      supplyPriceFlag: false,
      guidePriceFlag: false,
      ownerPs: null,
      storePs: null,
      platformMargin: null,
      specialPrice: null,
      goodsSource: 1,
      idNumber: null,
      purchasePrice: null,
      isGiftSku: null,
    },
  ],
  storeAveScore: null,
  storeFollowNum: 14,
  marketings: null,
  marketingVos: null,
  coupons: null,
  specs: [
    {
      id: "17",
      name: "军事用品",
      nickName: null,
      delFlag: "0",
      createName: null,
      modifyName: null,
      delName: null,
      createTime: null,
      modifyTime: null,
      delTime: null,
      specValues: [
        {
          id: "76",
          specId: "17",
          name: "开刃",
          sort: 0,
          url: null,
          delFlag: null,
          createName: null,
          modifyName: null,
          delName: null,
          createTime: null,
          modifyTime: null,
          delTime: null,
        },
        {
          id: "77",
          specId: "17",
          name: "未开刃",
          sort: 0,
          url: null,
          delFlag: null,
          createName: null,
          modifyName: null,
          delName: null,
          createTime: null,
          modifyTime: null,
          delTime: null,
        },
      ],
    },
  ],
  list: [
    {
      id: "16082776626282700",
      name: "开刃",
      price: 100000.0,
      stock_num: 100,
      goods_id: "270",
      s1: "76",
      s2: null,
      s3: null,
      s4: null,
      s5: null,
      performanceScore: 0,
    },
    {
      id: "16082776626282701",
      name: "未开刃",
      price: 100000.0,
      stock_num: 100,
      goods_id: "270",
      s1: "77",
      s2: null,
      s3: null,
      s4: null,
      s5: null,
      performanceScore: 0,
    },
  ],
  skuCommentNum: 0,
  hasAtten: false,
  categories: null,
  storeScore: {
    storeId: "17",
    descScore: 4.6897,
    sellerScore: 4.6897,
    logisticsScore: 4.7586,
    storeInfo: {
      id: "17",
      storeName: "古天乐的杂货铺",
      status: "1",
      delFlag: null,
      reason: null,
      applyEnterTime: null,
      applyRenewalTime: null,
      enterTime: null,
      effectiveTime: null,
      createTime: "2023-02-28 09:15:00",
      modifyTime: null,
      closeTime: null,
      provinceId: null,
      cityId: null,
      districtId: null,
      contactDetailAddress: null,
      mobile: null,
      aveScore: null,
      avatarPicture:
        "https://wanshunfu-1301582899.cos.ap-guangzhou.myqcloud.com///bf073207f59ec2ecc068f450420c5f91.jpg",
      storeCompanyInfo: null,
      contactPerson: null,
      contactPhone: null,
      contactEmail: null,
      operator: null,
      bankName: null,
      bankUserName: null,
      bankAccount: null,
      branchBankAccount: null,
      branchBankName: null,
      operateType: null,
      accountBalance: null,
      idNumber: null,
      socialCreditCode: null,
      updateTime: null,
      enterpriseName: null,
      businessScope: null,
      spuNum: null,
      storeServiceVo: null,
      skus: null,
      hasAttention: null,
      storeServiceConfig: null,
      followNum: 14,
      location: null,
      storeCompanyInfoToAudit: false,
      renewalToAudit: false,
      remainingDays: 0,
      orgName: null,
      storeInfoOperatorLogList: null,
    },
  },
  brand: null,
  sku: {
    id: "16082776626282700",
    spuId: "270",
    skuNo: "1608277462000",
    name: "可小刀(开刃)",
    subTitle: "",
    stock: 100,
    warningStock: 10,
    supplyPrice: null,
    guidePrice: null,
    price: 1000.0,
    weight: 1000.0,
    storeId: "17",
    storeName: null,
    isDefault: 0,
    isBatchSku: 0,
    shelvesStatus: "1",
    isGift: "0",
    isVirtual: "0",
    reason: null,
    delFlag: "0",
    createName: null,
    modifyName: null,
    delName: null,
    createTime: null,
    modifyTime: null,
    delTime: null,
    isShow: 1,
    accumulativeStock: 0,
    url: "https://wanshunfu-1301582899.cos.ap-guangzhou.myqcloud.com///acbdc92b567048edc00ce6a223f272ae.jpg?fileUid=1608277448612",
    status: "0",
    firstCateId: "62",
    secondCateId: "63",
    thirdCateId: "64",
    upTime: "2020-12-30 16:45:29",
    skuImages: [
      {
        id: "5364",
        spuId: "270",
        skuId: "16082776626282700",
        url: "https://wanshunfu-1301582899.cos.ap-guangzhou.myqcloud.com///acbdc92b567048edc00ce6a223f272ae.jpg?fileUid=1608277448612",
        defaultFlag: null,
        delFlag: "0",
      },
    ],
    skuSpecValues: [
      {
        id: "7012",
        spuId: "270",
        skuId: "16082776626282700",
        specId: "17",
        specValueId: "76",
        valueRemark: "开刃",
        delFlag: "0",
        specValueSource: 0,
        spec: {
          id: "17",
          name: "军事用品",
          nickName: "危险 慎用",
          delFlag: "0",
          createName: "admin",
          modifyName: null,
          delName: null,
          createTime: null,
          modifyTime: null,
          delTime: null,
          specValues: null,
        },
      },
    ],
    nameSkus: null,
    initialSku: { s1: "76", s2: null, s3: null, s4: null, s5: null },
    tree: [
      {
        k: "军事用品",
        k_id: "17",
        v: [
          { id: "76", name: "开刃", imgUrl: null },
          { id: "77", name: "未开刃", imgUrl: null },
        ],
        k_s: "s1",
        count: 2,
      },
    ],
    specValues: null,
    remark: null,
    mobileDesc: null,
    logisticsTemplateId: "14",
    performanceScore: 0,
    skuNum: null,
    unitId: null,
    grossProfitMargin: null,
    supplyPriceFlag: false,
    guidePriceFlag: false,
    ownerPs: null,
    storePs: null,
    platformMargin: null,
    specialPrice: null,
    goodsSource: 1,
    idNumber: null,
    purchasePrice: null,
    isGiftSku: null,
  },
  pcDesc: null,
  mobileDesc: "",
  mobileImageUrlList: null,
  detailIsNew: 0,
  video: "",
  videoPic: "",
  spuVideo: null,
  spuVideoPic: null,
  sellOut: 0,
  preCommission: null,
  tabooStatus: null,
  shelvesStatus: "1",
  performanceScore: 0,
  storeServiceConfig: {
    uid: "122039_",
    name: "万顺福_oiYxEM1y0f",
    email: null,
    mobile: "15007170117",
    staffId: null,
    groupId: null,
  },
  shareImage:
    "https://wanshunfu-1301582899.cos.ap-guangzhou.myqcloud.com///acbdc92b567048edc00ce6a223f272ae.jpg?fileUid=1608277448612",
  afterCouponPrice: null,
  couponLabelList: [],
  haveCoupon: false,
  skuLable: {
    spuId: "270",
    skuId: "16082776626282700",
    finalPrice: null,
    couponLable: null,
    markIngLabel: null,
    performanceScoreLabel: { performanceScore: 0, skuId: "16082776626282700" },
    baseLabel: {
      skuId: "16082776626282700",
      comment: 0,
      applauseRate: "0",
      salesVolume: 2,
      url: null,
      name: null,
      subTitle: null,
      price: null,
    },
  },
  marketingPrice: false,
};
